### ISSUE TITLE
导入问题

### ISSUE THREAD

**Issue by ethanchengyu** [JakeLaoyu/memos-import-from-flomo#19]
请问支持windows环境下导入吗

**Comment by ethanchengyu** [comment]
> 请问支持windows环境下导入吗

另外your-api-host从哪里找？

**Comment by ethanchengyu** [comment]
我直接用的官方demo注册的，没有自己部署的服务器，怎么填写？

**Comment by JakeLaoyu** [comment]
官方demo 会清除数据的吧

**Comment by ethanchengyu** [comment]
好吧，我发布的都是未公开的，三天了还没看到被删除，这玩意还要自己买服务器才能用？

**Comment by JakeLaoyu** [comment]
肯定的，官方 demo 肯定不保证数据的，数据存储也是有成本的

**Comment by ethanchengyu** [comment]
算了，老老实实用回flomo吧

**Comment by Chefback** [comment]
> 有node环境就行。 api host 在你自己部署的服务设置里

你好，api host在服务设置里没有，还是说就是部署的服务器的域名或ip？ 可是输入IP报错，AxiosError '127.0.0.1' 'ECONNREFUSED'

**Comment by ethanchengyu** [comment]
> 有node环境就行。 api host 在你自己部署的服务设置里

求帮助，具体怎么操作呢？我以为要买服务器

**Comment by JakeLaoyu** [comment]
> > 有node环境就行。 api host 在你自己部署的服务设置里
> 
> 求帮助，具体怎么操作呢？我以为要买服务器

api host 就是域名，demo 应该是 https://demo.usememos.com

**Comment by ethanchengyu** [comment]
> > > > 有node环境就行。 api host 在你自己部署的服务设置里
> > > 
> > > 
> > > 求帮助，具体怎么操作呢？我以为要买服务器
> > 
> > 
> > api host 就是域名，demo 应该是 https://demo.usememos.com
> 
> 不好意思，我编程不是太懂，我就是想弄明白他说的由node环境就行，我已经用终端装了node16.0，然后在哪里找我的api host 我用AI帮我解答了一下，不知道能不能行，我先试着一步步来，不懂了还得麻烦大佬 1.**创建一个新的 Node.js 项目**
> 
> * 在您想要创建项目的目录中，打开终端并输入以下命令：
>   ```
>   npm init -y
>   ```
> * 这将创建一个名为 `package.json` 的文件，其中包含有关您的项目的元数据。
> 
> 2. **安装 Express.js**
>    
>    * 在终端中，输入以下命令：
>      ```
>      npm install express
>      ```
>    * 这将安装 Express.js 并将其添加到您的 `node_modules` 目录中。
> 3. **创建服务器**
>    
>    * 在您的项目目录中，创建一个名为 `server.js` 的文件。
>    * 在 `server.js` 文件中，添加以下代码：
>      ```
>      const express = require('express');
>      const app = express();
>      
>      app.get('/', (req, res) => {
>        res.send('Hello, world!');
>      });
>      
>      app.listen(3000, () => {
>        console.log('Server listening on port 3000');
>      });
>      ```
>    * 这段代码创建了一个简单的 HTTP 服务器，当客户端向服务器发送 `GET` 请求时，服务器将响应 `Hello, world!`。
> 4. **启动服务器**
>    
>    * 在终端中，进入您的项目目录并输入以下命令：
>      ```
>      node server.js
>      ```
>    * 这将启动服务器，您应该会看到以下输出：
>      ```
>      Server listening on port 3000
>      ```
> 5. **测试服务器**
>    
>    * 在浏览器中，导航到以下 URL：
>      ```
>      http://localhost:3000
>      ```
>    * 您应该会看到以下内容：
>      ```
>      Hello, world!
>      ```
> 
> 至此，您已经成功地创建了一个简单的 Node.js 服务器。
> 
> **注意：**
> 
> * 上述步骤假设您已经安装了 Node.js 和 npm。如果您尚未安装，请按照以下步骤操作：
>   
>   * 下载并安装 Node.js。
>   * 打开终端并输入以下命令：
>     ```
>     npm install -g npm
>     ```
> * 您可以在任何地方找到您的 API 主机。它通常是一个 URL，例如 `https://example.com/api`。
> * 如果您想在本地测试您的 API，您可以使用 `localhost` 作为您的 API 主机。

服务器是创建成功了，但是我把http://localhost:3000填入服务器中，就显示<!DOCTYPE html> <html lang="en"> <head>...数据解析错误，搞不懂

**Comment by JakeLaoyu** [comment]
@ethanchengyu 你把这个仓库代码拉下来，执行一下 npm install，然后使用 文档中的 node 命令执行就好了
