### ISSUE TITLE
小白提问，最后一步运行脚本时提示 no matches found

### ISSUE THREAD

**Issue by gaoran1209** [JakeLaoyu/memos-import-from-flomo#2]
![image](https://user-images.githubusercontent.com/15261543/218634849-8fed3af9-6d2e-429d-8d5a-6e49b1bfd625.png)

如图
前几步都正常操作了，最后一步导入提示 no matches found，是我 OpenAPI 填入的方式不对么？

**Comment by JakeLaoyu** [comment]
openapi 不需要 [], 我调整一下文档

**Comment by JakeLaoyu** [comment]
建议等 memos 发布 0.10.4 再倒入，现在还不支持同步创建时间 https://github.com/usememos/memos/pull/1072

**Comment by gaoran1209** [comment]
感谢回复！

所以不需要填入自己的 openapi 地址么？这样的话，导入的 memos 是导入到哪个账号呢？
是需要在本地环境中跑么？

（背景是，我的 memos 跑在家里的 nas 上，在公司的电脑上按上面的解法改完以后没有导入成功。
本人不懂代码，没看懂代码的实现）

**Comment by JakeLaoyu** [comment]
需要 openApi 地址，但是不需要那个括号，那个括号我的本意是变量的意思。看起来你第一次执行的命令是对的。no-matches 应该是你电脑访问不到这个地址吧。你执行命令的这台电脑可以直接访问你的域名吗
<img width="645" alt="image" src="https://user-images.githubusercontent.com/16181940/218656890-02095172-8306-48a0-825c-1b40bc898fc0.png">

**Comment by gaoran1209** [comment]
![image](https://user-images.githubusercontent.com/15261543/218658193-d40406b3-279f-4230-95d5-9fe57e1db20b.png)
可以的，我试了一下，无论是 https 还是 http，都是可以访问的。
在浏览器中直接访问 api 接口的结果如上。

执行这两个命令，得到的都是 no matches found
`ryan@RYAN-MacBookPro memos-import-from-flomo % node ./src/main.js http://nas.gaoran.xyz:5230/api/memo?openId=39dXXXXXX4e2 ./flomo/index.html
`
`ryan@RYAN-MacBookPro memos-import-from-flomo % node ./src/main.js https://nas.gaoran.xyz:5231/api/memo?openId=39XXXXXXXX4e2 ./flomo/index.html`

**Comment by JakeLaoyu** [comment]
试试在终端里用 curl 访问一下你的 open api

**Comment by gaoran1209** [comment]
直接访问也是返回 no matches
![image](https://user-images.githubusercontent.com/15261543/218664295-19462e50-44fd-4742-8249-8954a1610c38.png)

**Comment by JakeLaoyu** [comment]
看起来是你终端有问题，检查一下终端是否有代理之类的

**Comment by gaoran1209** [comment]
好吧， 我测试了一下，curl 连接 nas 上的其他服务，包括访问 memos 都是可以的。
唯独 memos 的 api 地址返回 nomatches。重置了 api 也还是不行。
看起来应该是我自己的个性化问题。不浪费您的时间了！

感谢解答！！

**Comment by jcywong** [comment]
我也是遇到了这个问题，但是解决了，用单引号将api包起来

> 好吧， 我测试了一下，curl 连接 nas 上的其他服务，包括访问 memos 都是可以的。 唯独 memos 的 api 地址返回 nomatches。重置了 api 也还是不行。 看起来应该是我自己的个性化问题。不浪费您的时间了！
> 
> 感谢解答！！
