### ISSUE TITLE
[新特性请求]能否在每个块导入前先检测是否存在

### ISSUE THREAD

**Issue by a15355447898a** [JakeLaoyu/memos-import-from-flomo#26]
当flomo导入memos在中途失败后,目前我只能手动处理flomo中可能引起错误的文本,回滚memos数据,然后再次尝试导入,这非常的不方便
如果在每个块导入前能先检查是否存在,然后增量导入就好了

**Comment by JakeLaoyu** [comment]
@a15355447898a 检测是否存量很难判断

加了错误处理，报错也不会影响已经上传过的 ID 保存，可以使用下面的方式清除已经上传的内容

`node ./src/delete.js <your-api-host> <your-access-token>`

#28
