### ISSUE TITLE
能否增加批量md文件导入功能？

### ISSUE THREAD

**Issue by jxjxjhjh** [JakeLaoyu/memos-import-from-flomo#29]
原来是用obsidian的，其他文件我都手动导入或放弃了，但日记文件不能放弃，又因为数量太多无法手动导入，能否增加手动导入功能？

我的日记文件格式是 2020-01-01.md 这样的

**Comment by JakeLaoyu** [comment]
@jxjxjhjh 这种自定义文件没有固定的格式，不太好统一处理，你希望的命令是什么样的呢

**Comment by jxjxjhjh** [comment]
> @jxjxjhjh 这种自定义文件没有固定的格式，不太好统一处理，你希望的命令是什么样的呢

获取文件名中的日期为memos中的发表日期，时间就设置一个同一时间即可。
既然是md文件，就直接导入文字即可，memos本身也是支持md格式的。

其实导入要求就2点，一个是日期不要乱，二是能正常导入显示即可，只要文本正常即可，能识别标题和标签就行了，其他就不奢求了。
