### ISSUE TITLE
请问能修改一份适合Version: v0.23.0版本的吗？

### ISSUE THREAD

**Issue by jump1999** [JakeLaoyu/memos-import-from-flomo#32]
0.23.0版本修改了新的api，会有一些不一样，导致导入报错了。

**Comment by JakeLaoyu** [comment]
@jump1999 0.23.0 还没发稳定版

**Comment by chriscurrycc** [comment]
现在发版了，兄弟

**Comment by JakeLaoyu** [comment]
@chriscurrycc 看起来最新的提交支持了 0.23.0 #33

**Comment by chriscurrycc** [comment]
感谢，我看 memos 好像也没有最新的接口文档，请问你是怎么知道知道接口结构的，直接看源码吗？ 

https://github.com/usememos/memos/issues/2906
