### ISSUE TITLE
执行 flomo 导入脚本时提示 404

### ISSUE THREAD

**Issue by zengyun-hacker** [JakeLaoyu/memos-import-from-flomo#6]
在执行 `node ./src/main.js openApi ./flomo/index.html`脚本时，在第一步执行`uploadFileHandler`时 response 返回 404，具体错误为
```
data: { error: 'code=404, message=Not Found', message: 'Not Found' }
```
出错的 path 为 `/api/resource/blob?openId=xxx`

memos 版本为 `v0.14.2`，不确定是否是这个 API 失效导致的，翻了下也没找到 memos 的官方 API 文档，所以来弱弱提个 issue

**Comment by JakeLaoyu** [comment]
#7 

feat/new-version-api

麻烦切换到这个分支再试一下

**Comment by zengyun-hacker** [comment]
OK了~ 回复速度惊人代码更新速度也非常惊人！

**Comment by JakeLaoyu** [comment]
刚好看到，THX
